import sqlite3, json, os
from datetime import datetime

DB_PATH = os.getenv("DB_PATH", "./interview.db")
AUDIO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "audio")

def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    os.makedirs(AUDIO_DIR, exist_ok=True)

    conn = get_conn()

    # Sessions
    conn.execute("""
        CREATE TABLE IF NOT EXISTS sessions (
            id TEXT PRIMARY KEY,
            job_description TEXT,
            resume_text TEXT,
            difficulty INTEGER,
            seniority_bar TEXT,
            time_limit INTEGER,
            questions TEXT,
            answers TEXT DEFAULT '{}',
            status TEXT DEFAULT 'active',
            report TEXT,
            created_at TEXT,
            completed_at TEXT
        )
    """)

    # Add verify_coding_ability column to sessions (safe migration for existing DBs)
    try:
        conn.execute("ALTER TABLE sessions ADD COLUMN verify_coding_ability INTEGER DEFAULT 0")
    except Exception:
        pass  # Column already exists

    # Add draw_answers column to sessions (stores JSON array of base64 PNGs)
    try:
        conn.execute("ALTER TABLE sessions ADD COLUMN draw_answers TEXT")
    except Exception:
        pass  # Column already exists

    # Settings
    conn.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT
        )
    """)

    # Question bank — shared, reusable across jobs
    conn.execute("""
        CREATE TABLE IF NOT EXISTS questions (
            id TEXT PRIMARY KEY,
            domain TEXT NOT NULL,
            difficulty INTEGER NOT NULL,
            question TEXT NOT NULL,
            voice_text TEXT,
            topic TEXT,
            audio_path TEXT,
            created_at TEXT
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_questions_domain ON questions(domain, difficulty)")

    # Job setup state — tracks background question/audio generation per job
    conn.execute("""
        CREATE TABLE IF NOT EXISTS job_setup (
            job_id INTEGER PRIMARY KEY,
            domain TEXT,
            difficulty INTEGER,
            seniority TEXT,
            num_technical INTEGER,
            num_behavioral INTEGER,
            status TEXT DEFAULT 'pending',
            progress_current INTEGER DEFAULT 0,
            progress_total INTEGER DEFAULT 0,
            question_ids TEXT DEFAULT '[]',
            created_at TEXT,
            updated_at TEXT
        )
    """)

    # Seed default evaluation prompt
    existing = conn.execute("SELECT key FROM settings WHERE key = 'evaluation_prompt'").fetchone()
    if not existing:
        default_prompt = """Important evaluation guidelines:
- The transcript was generated by a speech-to-text system and may contain transcription errors, especially for technical terms, names, or candidates with non-native English accents. Do NOT penalize for these errors.
- Focus on the overall intent and technical correctness of each answer. If a word appears mis-transcribed, infer the most likely intended meaning from context.
- Evaluate technical depth, correctness, and understanding — not grammar, accent, or language fluency.
- Communication score should reflect clarity of explanation and logical structure, not language proficiency.
- For skipped questions, score 0."""
        conn.execute("INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?)",
            ('evaluation_prompt', default_prompt, datetime.now().isoformat()))

    conn.commit()
    conn.close()
