import sqlite3, json, os
from datetime import datetime

DB_PATH = os.getenv("DB_PATH", "./interview.db")

def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_conn()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS sessions (
            id TEXT PRIMARY KEY,
            job_description TEXT,
            resume_text TEXT,
            difficulty INTEGER,
            seniority_bar TEXT,
            time_limit INTEGER,
            questions TEXT,
            answers TEXT DEFAULT '{}',
            status TEXT DEFAULT 'active',
            report TEXT,
            created_at TEXT,
            completed_at TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT
        )
    """)
    # Seed default evaluation prompt if not set
    existing = conn.execute("SELECT key FROM settings WHERE key = 'evaluation_prompt'").fetchone()
    if not existing:
        default_prompt = """Important evaluation guidelines:
- The transcript was generated by a speech-to-text system and may contain transcription errors, especially for technical terms, names, or candidates with non-native English accents. Do NOT penalize for these errors.
- Focus on the overall intent and technical correctness of each answer. If a word appears mis-transcribed, infer the most likely intended meaning from context.
- Evaluate technical depth, correctness, and understanding — not grammar, accent, or language fluency.
- Communication score should reflect clarity of explanation and logical structure, not language proficiency.
- For skipped questions, score 0."""
        conn.execute("INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?)",
            ('evaluation_prompt', default_prompt, datetime.now().isoformat()))
    conn.commit()
    conn.close()
